# Base image
FROM node:20-bullseye
# Set working directory
WORKDIR /src
# Copy dependencies
COPY package*.json ./
# Install dependencies
RUN npm install
# Copy source files
COPY ./src .
COPY ./tsconfig.json ./tsconfig.json
# Build with typescript
RUN npm run build
# production env variable
# the rest will be loaded with compose or cmd
ENV NODE_ENV=production
# Expose port 
EXPOSE 9000
# Start the app
CMD ["node", "dist/index.js"]